/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dwd_jni_GetTime */

#ifndef _Included_com_dwd_jni_GetTime
#define _Included_com_dwd_jni_GetTime
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dwd_jni_GetTime
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_dwd_jni_GetTime_hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
